name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/edge/install)"
          PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          npm install -g npm@7
          npm install
          npm run build
          ls -l lib
          test -r lib/index.iife.js
          test -r lib/index.cjs.js
          test -r lib/index.esm.js
          npm run ok
          npm run codecov
          npm run test:live-with-test-validator

      - name: Publish NPM
        run: |
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Github Page
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
